### ISSUE TITLE
panic: runtime error: cgo argument has Go pointer to Go pointer

### ISSUE THREAD

**Issue by gene-hightower** [gleez/smtpd#5]
$ $GOPATH/bin/smtpd -config=/a/src/smtpd/smtpd.conf 
2018/01/06 19:59:34 [INFO ] Smtpd 1.1 (undefined) starting...
2018/01/06 19:59:34 [INFO ] Incus Websocket Init
2018/01/06 19:59:34 [INFO ] Theme templates mapped to './themes/cerber/templates'
2018/01/06 19:59:34 [INFO ] Theme static content mapped to './themes/cerber/public'
2018/01/06 19:59:34 [TRACE] Loading the certificate: smtp.pem
2018/01/06 19:59:34 [INFO ] HTTP listening on TCP4 0.0.0.0:10025
2018/01/06 19:59:34 [INFO ] SMTP listening on TCP4 0.0.0.0:25000
2018/01/06 19:59:34 [INFO ] Trying MongoDB storage
2018/01/06 19:59:34 [TRACE] Connecting to MongoDB: 127.0.0.1:27017
2018/01/06 19:59:34 [INFO ] Using MongoDB storage
2018/01/06 19:59:34 [TRACE] Running SaveMail Rotuines
2018/01/06 19:59:34 [TRACE] Running SaveMail Rotuines
2018/01/06 19:59:34 [TRACE] Running SaveMail Rotuines
2018/01/06 19:59:42 [TRACE] Web: [::1]:44686 HTTP/1.1 GET /
2018/01/06 19:59:42 [TRACE] Parsing template themes/cerber/templates/root/index.html
2018/01/06 20:00:01 [TRACE] Web: [::1]:44690 HTTP/1.1 GET /login
2018/01/06 20:00:01 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:00:07 [TRACE] Web: [::1]:44690 HTTP/1.1 GET /status
2018/01/06 20:00:07 [TRACE] This page requires a login.
2018/01/06 20:00:07 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:00:11 [TRACE] Web: [::1]:44690 HTTP/1.1 GET /mails
2018/01/06 20:00:11 [TRACE] Loading Mails from Mongodb
2018/01/06 20:00:11 [TRACE] This page requires a login.
2018/01/06 20:00:11 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:04:58 [TRACE] Web: [::1]:44782 HTTP/1.1 GET /
2018/01/06 20:04:58 [TRACE] Parsing template themes/cerber/templates/root/index.html
2018/01/06 20:05:03 [TRACE] Web: [::1]:44784 HTTP/1.1 GET /status
2018/01/06 20:05:03 [TRACE] This page requires a login.
2018/01/06 20:05:03 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:05:12 [TRACE] Web: [::1]:44784 HTTP/1.1 GET /register
2018/01/06 20:05:12 [TRACE] Parsing template themes/cerber/templates/common/signup.html
2018/01/06 20:05:41 [TRACE] Web: [::1]:44784 HTTP/1.1 POST /register
2018/01/06 20:05:41 [TRACE] Registration successful
2018/01/06 20:05:41 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:05:51 [TRACE] Web: [::1]:44784 HTTP/1.1 POST /login
2018/01/06 20:05:51 [TRACE] Login successful for session <ObjectIdHex("5a519c950113894fb55ae5b9")>
2018/01/06 20:05:51 [TRACE] The user is not activated
2018/01/06 20:05:51 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:07:19 [TRACE] Web: [::1]:44794 HTTP/1.1 POST /login
2018/01/06 20:07:19 [TRACE] Login successful for session <ObjectIdHex("5a519c950113894fb55ae5b9")>
2018/01/06 20:07:19 [TRACE] The user is not activated
2018/01/06 20:07:19 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:07:28 [TRACE] Web: [::1]:44794 HTTP/1.1 GET /register
2018/01/06 20:07:28 [TRACE] Parsing template themes/cerber/templates/common/signup.html
2018/01/06 20:07:52 [TRACE] Web: [::1]:44794 HTTP/1.1 POST /register
2018/01/06 20:07:52 [TRACE] Registration successful
2018/01/06 20:07:52 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:07:55 [TRACE] Web: [::1]:44794 HTTP/1.1 GET /
2018/01/06 20:07:55 [TRACE] Parsing template themes/cerber/templates/root/index.html
2018/01/06 20:07:57 [TRACE] Web: [::1]:44794 HTTP/1.1 GET /status
2018/01/06 20:07:57 [TRACE] This page requires a login.
2018/01/06 20:07:57 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:07:58 [TRACE] Web: [::1]:44794 HTTP/1.1 POST /login
2018/01/06 20:07:58 [TRACE] Login successful for session <ObjectIdHex("5a519c950113894fb55ae5b9")>
2018/01/06 20:07:58 [TRACE] The user is not activated
2018/01/06 20:07:58 [TRACE] Parsing template themes/cerber/templates/common/login.html
2018/01/06 20:08:56 [INFO ] There are now 16 serving goroutines
2018/01/06 20:08:56 [INFO ] SMTP Connection from 127.0.0.1:40490, starting session <1>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 62 bytes: smtpd.local Gleez SMTP # 1 (1) Sat, 06 Jan 2018 20:08:56 -0800 >>
2018/01/06 20:08:56 [INFO ] SMTP[127.0.0.1]<1> Remote Client is Trusted: <127.0.0.1>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> << EHLO digilicious.com <<
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> In state 1, got command 'EHLO', args 'digilicious.com'
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 32 bytes: Hello digilicious.com[127.0.0.1] >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 10 bytes: PIPELINING >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 8 bytes: 8BITMIME >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 8 bytes: STARTTLS >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 34 bytes: AUTH EXTERNAL CRAM-MD5 LOGIN PLAIN >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 13 bytes: SIZE 20480000 >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> << STARTTLS <<
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> In state 1, got command 'STARTTLS', args ''
2018/01/06 20:08:56 [TRACE] Ready to start TLS
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 18 bytes: Ready to start TLS >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> << EHLO digilicious.com <<
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> In state 1, got command 'EHLO', args 'digilicious.com'
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 32 bytes: Hello digilicious.com[127.0.0.1] >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 10 bytes: PIPELINING >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 8 bytes: 8BITMIME >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 34 bytes: AUTH EXTERNAL CRAM-MD5 LOGIN PLAIN >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 13 bytes: SIZE 20480000 >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> << MAIL FROM:<test-it@digilicious.com> SIZE=3445 BODY=8BITMIME <<
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> In state 1, got command 'MAIL', args 'FROM:<test-it@digilicious.com> SIZE=3445 BODY=8BITMIME'
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> ESMTP params: map[SIZE:3445 BODY:8BITMIME]
2018/01/06 20:08:56 [INFO ] SMTP[127.0.0.1]<1> Mail from: test-it@digilicious.com
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 52 bytes: Roger, accepting mail from <test-it@digilicious.com> >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> << RCPT TO:<test-it@digilicious.com> <<
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> In state 1, got command 'RCPT', args 'TO:<test-it@digilicious.com>'
2018/01/06 20:08:56 [INFO ] SMTP[127.0.0.1]<1> Recipient: test-it@digilicious.com
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 50 bytes: I'll make sure <test-it@digilicious.com> gets this >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> << DATA <<
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> In state 1, got command 'DATA', args ''
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> Enter dataHandler 1
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> Go ahead we have recipients 1
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> >> Sent 46 bytes: Go ahead. End your data with <CR><LF>.<CR><LF> >>
2018/01/06 20:08:56 [TRACE] SMTP[127.0.0.1]<1> Got EOF, storing message and switching to MAIL state
2018/01/06 20:08:56 [TRACE] Reading Mail Message
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 22 [running]:
github.com/sloonz/go-iconv.(*Iconv).Conv.func1(0x7fc5bc000c20, 0xc4201f0088, 0xc420536c68, 0xc4201f0098, 0xc420536ce0, 0x200, 0x8, 0x8bf720)
	/z/home/gene/go/src/github.com/sloonz/go-iconv/iconv.go:60 +0x8b
github.com/sloonz/go-iconv.(*Iconv).Conv(0xc4201f0080, 0xc420175320, 0x1a, 0x0, 0xc4201f0080, 0x0, 0x0)
	/z/home/gene/go/src/github.com/sloonz/go-iconv/iconv.go:60 +0x1ef
github.com/sloonz/go-iconv.Conv(0xc420175320, 0x1a, 0x932ed8, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/z/home/gene/go/src/github.com/sloonz/go-iconv/iconv.go:79 +0xdd
github.com/gleez/smtpd/data.MimeHeaderDecode(0xc420175320, 0x1a, 0x7, 0xc4201752c0)
	/z/home/gene/go/src/github.com/gleez/smtpd/data/message.go:326 +0xf9
github.com/gleez/smtpd/data.ParseSMTPMessage(0xc42026cc80, 0xc420013767, 0xb, 0x1, 0x0)
	/z/home/gene/go/src/github.com/gleez/smtpd/data/message.go:104 +0xb7a
github.com/gleez/smtpd/data.(*DataStore).SaveMail(0xc4201b82a0)
	/z/home/gene/go/src/github.com/gleez/smtpd/data/storage.go:65 +0xc6
created by github.com/gleez/smtpd/data.(*DataStore).StorageConnect
	/z/home/gene/go/src/github.com/gleez/smtpd/data/storage.go:47 +0x157

**Comment by gene-hightower** [comment]
What am I doing wrong?  Any help appreciated.

**Comment by agussa** [comment]
Same as me when using thunderbird and adding subject in email. 
i just edit gleez/smtpd/data/message.go
in line #323 
if err == nil && charset != "UTF-8" {

add chek for empty charset. and the line become : 
if err == nil && charset != "UTF-8" && len(charset)>0 {

and rebuild again.
